# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine poetry
        pip install sphinx sphinx_rtd_theme
    - name: Build
      run: |
        poetry build # python -m build --sdist --wheel
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        # poetry publish --username="$TWINE_USERNAME" --password="$TWINE_PASSWORD"
        twine upload -u "$TWINE_USERNAME" -p "$TWINE_PASSWORD" dist/*
    
    
    
    - name: Sphinx build
      run: |
        sphinx-build -b html docs/source docs/build
    - name: Deploy Doc
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
